# Generated by Django 4.0.3 on 2022-04-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moringa',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
