# Generated by Django 4.0.3 on 2022-04-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_alter_moringa_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moringa',
        ),
    ]
